const menu = [
  {
    id: 1,
    title: 'Pear Necklace',
    category: 'necklace',
    price: 450,
    img: 'https://i.pinimg.com/474x/c7/d6/dd/c7d6ddca3fdda35f065d333acd81833c.jpg',
    desc: `I'm baby woke mlkshk wolf bitters live-edge blue bottle, hammock freegan copper mug whatever cold-pressed `,
  },
  {
    id: 2,
    title: 'Demi-Fine Gold Ring',
    category: 'rings',
    price: 800,
    img: 'https://i.pinimg.com/564x/7d/9b/10/7d9b10ef87c0206cbbca0fccbb692695.jpg',
    desc: `Enhance your look with unique demi-fine & fashion rings made to transform any outfit. Shop for high quality gold rings at Local Eclectic. `,
  },
  {
    id: 3,
    title: 'Earring Charm Jewelry',
    category: 'earings',
    price: 1500,
    img: 'https://i.pinimg.com/564x/78/3a/52/783a52ccb7af1d347eeb97e6fa6df5bb.jpg',
    desc: `ombucha chillwave fanny pack 3 wolf moon street art photo booth before they sold out organic viral.`,
  },
  {
    id: 4,
    title: 'Hoop Drop Earings',
    category: 'earings',
    price: 750,
    img: 'https://i.pinimg.com/564x/17/ed/ca/17edca909b2ec5c9f464e01130182644.jpg',
    desc: `Shabby chic keffiyeh neutra snackwave pork belly shoreditch. Prism austin mlkshk truffaut, `,
  },
  {
    id: 5,
    title: 'Vintage Flower Ring',
    category: 'rings',
    price: 800,
    img: 'https://i.pinimg.com/564x/eb/4a/65/eb4a65ab57e51b8f13cba8ff6c9860af.jpg',
    desc: `Daily Wear Gold Rings Designs For Women | My Jewellery Collection | Women Ring Designs 2020 | Engagement Rings Gold rings ,my jewellery collection,women ring designs 2019,engagement rings,daily wear… `,
  },
  {
    id: 6,
    title: 'Necklace',
    category: 'necklace',
    price: 1050,
    img: 'https://i.pinimg.com/564x/ac/c3/82/acc382efa4b2fbb9c2300fab9c65605e.jpg',
    desc: `Portland chicharrones ethical edison bulb, palo santo craft beer chia heirloom iPhone everyday`,
  },
  {
    id: 7,
    title: ' Rose Gold Ring',
    category: 'rings',
    price: 650,
    img: 'https://i.pinimg.com/564x/35/a2/28/35a228ef59f305b7d0dfedf50db1a15d.jpg',
    desc: `From stormy grey moissanite beauties to rose gold rings with peach colored stones, Etsy is home to some of the prettiest engagement rings out there. And guess what? Many of the rings cost less…
    More`,
  },
  {
    id: 8,
    title: ' Diamond Necklace',
    category: 'necklace',
    price: 900,
    img: 'https://i.pinimg.com/564x/40/0c/0c/400c0c67c53ac0b764a4717e19e5d88e.jpg',
    desc: `on it tumblr kickstarter thundercats migas everyday carry squid palo santo leggings. Food truck truffaut  `,
  },
  {
    id: 9,
    title: ' Diamond Earings',
    category: 'earings',
    price: 450,
    img: 'https://i.pinimg.com/564x/5c/1e/4f/5c1e4ffac6d0e569935f6177133b8318.jpg',
    desc: `Capture great deals on stylish Fashion Earrings from Swarovski, Betsey Johnson, Chanel & more. Shop our wide variety of products at the lowest online prices. Free shipping for many items!`,
  },
  {
    id: 10,
    title: 'Fashion Bangles',
    category: 'Bangles',
    price: 1700,
    img: 'https://i.pinimg.com/564x/e1/c3/42/e1c34247e1c3042d92be5769da317c37.jpg',
    desc: `Capture great deals on stylish Fashion Earrings from Swarovski, Betsey Johnson`,
  },
  {
    id: 11,
    title: 'Diamond Bangles',
    category: 'Bangles',
    price: 1900,
    img: 'https://i.pinimg.com/564x/21/0b/7f/210b7f3eddf7a5a62ac0ced24db7ff68.jpg',
    desc: `Capture great deals on stylish Fashion Earrings from Swarovski, Betsey Johnson`,
  },
  {
    id: 13,
    title: ' Indian Bangles',
    category: 'Bangles',
    price: 1400,
    img: 'https://i.pinimg.com/564x/7e/1d/be/7e1dbeccdaaf736f7ae53beae62e3b59.jpg',
    desc: `Capture great deals on stylish Fashion Earrings from Swarovski, Betsey Johnson`,
  },
];
export default menu;
